name: himacon
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
      - accelerate==0.34.2
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bleach==6.1.0
      - blis==0.7.11
      - braceexpand==0.1.7
      - catalogue==2.0.10
      - certifi==2024.8.30
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.19.0
      - comm==0.2.2
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.8
      - debugpy==1.8.6
      - decorator==4.4.2
      - diffusers==0.30.3
      - distlib==0.3.8
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fairscale==0.4.4
      - filelock==3.16.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - h5py==3.11.0
      - hdbscan==0.8.40
      - huggingface-hub==0.24.7
      - identify==2.6.0
      - idna==3.8
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kaggle==1.6.17
      - kiwisolver==1.4.7
      - langcodes==3.4.0
      - language-data==1.2.0
      - lazy-loader==0.4
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - murmurhash==1.0.10
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python-headless==4.10.0.84
      - opendatasets==0.1.22
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.2
      - plotly==5.24.1
      - portalocker==2.10.1
      - positional-encodings==6.0.3
      - pre-commit==3.8.0
      - preshed==3.0.9
      - proglog==0.1.10
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.8.1
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - spacy==3.8.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - sympy==1.13.2
      - tdqm==0.0.1
      - tenacity==9.0.0
      - text-unidecode==1.3
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timm==0.4.12
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchmetrics==1.4.2
      - torchvision==0.19.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.0.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.3
      - virtualenv==20.26.4
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.100
      - webencodings==0.5.1
      - wrapt==1.16.0
      - yarl==1.11.1
      - zipp==3.20.1
